/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1dd6426f-61f1-4c9e-901b-df6aeceea4a4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FbZQ0de7w",
    "aws_user_pools_web_client_id": "eupaprahrsd6344rd8b4duit7",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Users-main",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "cardgenprofilepictures233133-main",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "BusinessCardgenUserApi",
            "endpoint": "https://184oxjcry4.execute-api.us-east-1.amazonaws.com/main",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
